write_mode = "overwrite"

format_strings = false

reorder_imports = true

tab_spaces = 4
hard_tabs = true

match_block_trailing_comma = true

trailing_comma = "Vertical"

report_todo = "Always"
report_fixme = "Always"

max_width = 120


# more information
# https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md

