write_mode = "overwrite"

format_strings = false

reorder_imports = true
reorder_imported_names = true
reorder_imports_in_group = true

array_layout = "Block"
struct_lit_multiline_style = "ForceMulti"

tab_spaces = 4
hard_tabs = false

enum_trailing_comma = true
match_block_trailing_comma = true
struct_trailing_comma = "Always"
trailing_comma = "Vertical"
where_trailing_comma = true

report_todo = "Always"
report_fixme = "Always"

max_width = 120
ideal_width = 80
array_width = 120
fn_call_width = 120

#fn_args_density = "CompressedIfEmpty"

chain_indent = "Visual"
chain_one_line_max = 90

newline_style = "Unix"
normalize_comments = false
wrap_comments = true